version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '4200:3000'
        volumes:
            - /app/node_modules
            - .:/app
        stdin_open: true
        environment: 
            -  CHOKIDAR_USERPOLLING=true
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        environment: 
            - CHOKIDAR_USERPOLLING=true
        command: ["npm", "run", "test"]

